apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: existing-vsvc-1
spec:
  hosts:
  - 'hoge.tatchnicolas.com'
  http:
  - name: "ClusterIP"
    route:
    - destination:
        host: some-serivce-1.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: existing-vsvc-2
spec:
  hosts:
  - 'fuga.tatchnicolas.com'
  http:
  - name: "ClusterIP"
    route:
    - destination:
        host: some-serivce-2.default.svc.cluster.local
