apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-vsvc-host-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: vsvc-read-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vsvc-read-to-webhook
  namespace: default
subjects:
- kind: ServiceAccount
  name: istio-vsvc-host-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: vsvc-read-role
  apiGroup: ""
